# **Obtención y preparación de datos**

# OD16. Multi-Indexación de Estructuras en Pandas

Hasta ahora hemos visto series y dataframes pandas con índices sencillos, pero pueden tener también índices jerárquicos o multi-índices, lo que abre la puerta a sofisticados procesos de manipulación y análisis de datos.

Podemos imaginarnos un multi-índice como un índice en el que cada valor es una tupla única de elementos. Es posible crear estos multi-índices y extraerlos posteriormente de varias formas.

In [ ]:
import numpy as np
import pandas as pd

## <font color='blue'>**Creación de multi-índices**</font>

Podemos crear un multi-índice de cuatro formas distintas:

* A partir de una lista de arrays, usando el método **pd.MultiIndex.from_arrays()**
* A partir de un array de tuplas, usando el método **pd.MultiIndex.from_tuples()**
* A partir del producto cartesiano de los valores de dos iterables, usando el método **pd.MultiIndex.from_product()**
* A partir de un DataFrame, usando el método **pd.MultiIndex.from_frame()**

## <font color='blue'>**Multi-índices a partir de una lista de arrays**</font>

El primer método es aquel en el que creamos el multi-índice indicando cada una de las columnas que lo van a formar.

In [ ]:
index = pd.MultiIndex.from_arrays(
    [
        [2018, 2018, 2018, 2019, 2019, 2019],
        ["España", "Portugal", "Francia", "España", "Portugal", "Francia"]
    ],
    names = ["Año", "País"]
)
index

MultiIndex([(2018,   'España'),
            (2018, 'Portugal'),
            (2018,  'Francia'),
            (2019,   'España'),
            (2019, 'Portugal'),
            (2019,  'Francia')],
           names=['Año', 'País'])

El parámetro **names** permite especificar los nombres de los niveles del índice jerárquico.

Al llevar este multi-índice a un dataframe se obtiene el siguiente resultado:

In [ ]:
data = pd.DataFrame(data = [18, 20, 10, 15, 12, 18], index = index, columns = ["Ventas"])
data

               Ventas
Año  País
2018 España        18
     Portugal      20
     Francia       10
2019 España        15
     Portugal      12
     Francia       18

## <font color='blue'>**Multi-índices a partir de un array de tuplas**</font>

En este segundo método indicamos los valores del multi-índice valor por valor, siendo éstos tuplas.

In [ ]:
index = pd.MultiIndex.from_tuples(
    [
    (2018, "España"),
    (2018, "Portugal"),
    (2018, "Francia"),
    (2019, "España"),
    (2019, "Portugal"),
    (2019, "Francia")
    ],
    names = ["Año", "País"])
index

MultiIndex([(2018,   'España'),
            (2018, 'Portugal'),
            (2018,  'Francia'),
            (2019,   'España'),
            (2019, 'Portugal'),
            (2019,  'Francia')],
           names=['Año', 'País'])

Seguimos teniendo a nuestra disposición el parámetro names para especificar los nombres de los niveles.

Si creamos nuestro DataFrame vemos que el resultado es el mismo que el que habíamos obtenido:

In [ ]:
data = pd.DataFrame(data = [18, 20, 10, 15, 12, 18], index = index, columns = ["Ventas"])
data

               Ventas
Año  País
2018 España        18
     Portugal      20
     Francia       10
2019 España        15
     Portugal      12
     Francia       18

## <font color='blue'>**Multi-índices por producto cartesiano de arrays**</font>

El tercer método nos permite especificar los valores (únicos) de los diferentes niveles, creándose el índice jerárquico como resultado del producto escalar de los valores. Por ejemplo:

In [ ]:
index = pd.MultiIndex.from_product(
    [
        [2018, 2019],
        ["España", "Portugal", "Francia"]
    ],
    names = ["Año", "País"]
)
index

MultiIndex([(2018,   'España'),
            (2018, 'Portugal'),
            (2018,  'Francia'),
            (2019,   'España'),
            (2019, 'Portugal'),
            (2019,  'Francia')],
           names=['Año', 'País'])

Nuevamente, el parámetro names nos permite dar nombre a los niveles.

El resultado de llevar este índice a nuestro DataFrame es el ya conocido:

In [ ]:
data = pd.DataFrame(data = [18, 20, 10, 15, 12, 18], index = index, columns = ["Ventas"])
data

               Ventas
Año  País
2018 España        18
     Portugal      20
     Francia       10
2019 España        15
     Portugal      12
     Francia       18

## <font color='blue'>**Multi-índices a partir de un DataFrame**</font>

Por último, podemos crear el multi-índice a partir de un DataFrame en el que cada columna coincide con una columna del multi-índice.

In [ ]:
df = pd.DataFrame({
    "Año":[2018, 2018, 2018, 2019, 2019, 2019],
    "País": ["España", "Portugal", "Francia", "España", "Portugal", "Francia"]
})
df

    Año      País
0  2018    España
1  2018  Portugal
2  2018   Francia
3  2019    España
4  2019  Portugal
5  2019   Francia

Ahora podemos crear el índice:

In [ ]:
index = pd.MultiIndex.from_frame(df)
index

MultiIndex([(2018,   'España'),
            (2018, 'Portugal'),
            (2018,  'Francia'),
            (2019,   'España'),
            (2019, 'Portugal'),
            (2019,  'Francia')],
           names=['Año', 'País'])

DataFrame con índice jerárquico:

In [ ]:
data = pd.DataFrame(data = [18, 20, 10, 15, 12, 18], index = index, columns = ["Ventas"])
data

               Ventas
Año  País
2018 España        18
     Portugal      20
     Francia       10
2019 España        15
     Portugal      12
     Francia       18

## <font color='blue'>**Extracción de un nivel del índice**</font>

Trabajando con un DataFrame o una Serie pandas con multi-índice, es posible extraer los valores de un nivel del índice con el método **.get_level_values()**. El parámetro que deberemos pasar a este método será o el número del nivel o su nombre -si es que el índice ha recibido nombres-.

In [ ]:
index = pd.MultiIndex.from_product(
    [[2018, 2019],["España", "Portugal", "Francia"]],
    names = ["Año", "País"]
)
data = pd.DataFrame(data = [18, 20, 10, 15, 12, 18], index = index, columns = ["Ventas"])
data

               Ventas
Año  País
2018 España        18
     Portugal      20
     Francia       10
2019 España        15
     Portugal      12
     Francia       18

La columna de etiquetas del multi-índice situada en el extremo izquierdo es la que recibe el número (el índice) 0. Por lo tanto:

In [ ]:
data.index.get_level_values(0)

Int64Index([2018, 2018, 2018, 2019, 2019, 2019], dtype='int64', name='Año')

De forma semejante:

In [ ]:
data.index.get_level_values(1)

Index(['España', 'Portugal', 'Francia', 'España', 'Portugal', 'Francia'], dtype='object', name='País')

Si pasamos como argumento el nombre de la columna del índice obtenemos resultados semejantes:

In [ ]:
data.index.get_level_values("Año")

Int64Index([2018, 2018, 2018, 2019, 2019, 2019], dtype='int64', name='Año')

In [ ]:
data.index.get_level_values("País")

Index(['España', 'Portugal', 'Francia', 'España', 'Portugal', 'Francia'], dtype='object', name='País')

## <font color='blue'>**Selección con multi-índices**</font>

El trabajar con estructuras pandas con multi-índices nos ofrece nuevos métodos de selección de datos.

In [ ]:
index = pd.MultiIndex.from_product(
    [[2018, 2019],["España", "Portugal", "Francia"]],
    names = ["Año", "País"]
)
data = pd.DataFrame(data = [18, 20, 10, 15, 12, 18], index = index, columns = ["Ventas"])
data

               Ventas
Año  País
2018 España        18
     Portugal      20
     Francia       10
2019 España        15
     Portugal      12
     Francia       18

Podemos extraer las filas correspondientes al año 2018 con la siguiente expresión:

In [ ]:
data.loc[2018]

          Ventas
País
España        18
Portugal      20
Francia       10

O extraer el valor del campo "Ventas" correspondiente al año 2018 y el país "España" con la siguiente expresión:

In [ ]:
data.loc[(2018, "España")]

Ventas    18
Name: (2018, España), dtype: int64

## <font color='blue'>**Aplicación de funciones estadísticas**</font>

Usando multi-índices, también es posible aplicar funciones estadísticas al DataFrame o a la Serie especificando el nivel de la jerarquía al que aplicarlas.

In [ ]:
index = pd.MultiIndex.from_product(
    [[2018, 2019],["España", "Portugal", "Francia"]],
    names = ["Año", "País"]
)
data = pd.DataFrame(data = [18, 20, 10, 15, 12, 18], index = index, columns = ["Ventas"])
data

               Ventas
Año  País
2018 España        18
     Portugal      20
     Francia       10
2019 España        15
     Portugal      12
     Francia       18

Podemos calcular el valor medio de las ventas, como ya sabemos con el método .mean():

In [ ]:
data.mean()

Ventas    15.5
dtype: float64

Pero si especificamos el nivel al que queremos aplicarlo, el DataFrame se agrega según los valores de dicho nivel antes de realizar la operación.

In [ ]:
data.mean(level = "Año")

      Ventas
Año
2018      16
2019      15

O el valor medio por país:

In [ ]:
data.mean(level = "País")

          Ventas
País
España      16.5
Portugal    16.0
Francia     14.0

In [ ]:
data.mean(level = ["Año","País"])

               Ventas
Año  País
2018 España        18
     Portugal      20
     Francia       10
2019 España        15
     Portugal      12
     Francia       18